<%-- 
    Document   : CadastroImg
    Created on : 17/02/2015, 13:46:17
    Author     : Valdomiro
--%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>

<% 
      if(session.getValue("loginUsuario") == null && session.getValue("senhaUsuario") == null){
            response.sendRedirect("Home.jsp");
       }else 
       {
           String permissao= (String) session.getValue("permissaoUsuario");
           String array[] = new String[4];  
           array = permissao.split("-");
           if(array[1].toString().charAt(1)!='1'){
             response.sendRedirect("Home.jsp");
           }
       }
    %>

<!DOCTYPE HTML>
<html lang="pt">
   <head>
    <!-- Force latest IE rendering engine or ChromeFrame if installed -->
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
        <meta charset="utf-8">
        <title></title>
        <meta name="description" content="File Upload widget with multiple file selection, drag&amp;drop support, progress bars, validation and preview images, audio and video for jQuery. Supports cross-domain, chunked and resumable file uploads and client-side image resizing. Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- <link rel="stylesheet" href="jquery/validar.js">-->
      <link rel=stylesheet type="text/css" href="css/novo.css">
       <link rel="stylesheet" href="jquery/validate.js">
       <link rel="stylesheet" href="jquery/jquery-1.js">
        <link rel="stylesheet" href="css/form.css">
    <!-- Bootstrap styles -->
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <!-- Generic page styles -->
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="css/breadcrumb.css">
        <!-- blueimp Gallery styles -->
        <link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
        <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
        <link rel="stylesheet" href="css/jquery.fileupload.css">
        <link rel="stylesheet" href="css/jquery.fileupload-ui.css">
        <!-- CSS adjustments for browsers with JavaScript disabled -->
        <noscript><link rel="stylesheet" href="css/jquery.fileupload-noscript.css"></noscript>
        <noscript><link rel="stylesheet" href="css/jquery.fileupload-ui-noscript.css"></noscript>
        <style type="text/css">
.css_btn_class {
	font-size:16px;
	font-family:Arial;
	font-weight:normal;
	-moz-border-radius:8px;
	-webkit-border-radius:8px;
	border-radius:8px;
	border:1px solid #74b807;
	padding:9px 18px;
	text-decoration:none;
	background:-moz-linear-gradient( center top, #89c403 56%, #77a809 49% );
	background:-ms-linear-gradient( top, #89c403 56%, #77a809 49% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#89c403', endColorstr='#77a809');
	background:-webkit-gradient( linear, left top, left bottom, color-stop(56%, #89c403), color-stop(49%, #77a809) );
	background-color:#89c403;
	color:#ffffff;
	display:inline-block;
	text-shadow:1px 1px 0px #528009;
 	-webkit-box-shadow:inset 1px 1px 0px 0px #a4e271;
 	-moz-box-shadow:inset 1px 1px 0px 0px #a4e271;
 	box-shadow:inset 1px 1px 0px 0px #a4e271;
}.css_btn_class:hover {
	background:-moz-linear-gradient( center top, #77a809 56%, #89c403 49% );
	background:-ms-linear-gradient( top, #77a809 56%, #89c403 49% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77a809', endColorstr='#89c403');
	background:-webkit-gradient( linear, left top, left bottom, color-stop(56%, #77a809), color-stop(49%, #89c403) );
	background-color:#77a809;
}.css_btn_class:active {
	position:relative;
	top:1px;
}
.css_btn_class{
 
    margin-top: 1px;
    margin-left: 940px;
}
/* This css button was generated by css-button-generator.com */
</style>
       

        
        </head>
    <body>
        <jsp:useBean id="res" class="meupacote.processa" />
        <% 
            String traducao="";
               Cookie cookie = null; 
               Cookie[] cookies = null;
               cookies = request.getCookies(); 
           
           if(traducao.isEmpty()){
               
               if(cookies.length<=1){
                    Cookie trad= new Cookie("Traducao","por");
                    trad.setMaxAge(60*60*24);
                    response.addCookie(trad);
                    
                    
               }
                Cookie ck = null; 
                Cookie[] cks = null;
                cks = request.getCookies();
                 for (int i = 0; i < cks.length; i++)
                        { 
                            ck = cks[i]; 
                            if(ck.getName().equals("Traducao")){

                                traducao = ck.getValue();
                                

                            }
                            //out.print("Traducao cabecalho "+ ck.getValue());
                        }
                 
                 
                
           }else{
               
               if( cookies == null ){
                out.print("não existe cookies");
               }else{
                //out.print("Tamanho do cookie "+cookies.length);
                    for (int i = 0; i < cookies.length; i++)
                    { 
                        cookie = cookies[i]; 
                        if(cookie.getName().equals("Traducao")){

                            traducao = cookie.getValue();

                        }
                    }
              }
            
           }
         
       %>
        <div class="tradutor">
            
             <button type="submit" name="brasil" value="0" id="bras"><a href="#" title="Portugês (Brasil)"><img src=".\imagens\brasil.png" /></a></button>
         
        
             <button type="submit" name="espanhol" value="1" id="esp"><a href="#" title="Espanhol (Espanha)"><img src=".\imagens\espanha.png" /></a></button>
           
             
               <button type="submit" name="ingles" value="2" id="eng"><a href="#" title="Inglês (Americano)"><img src=".\imagens\EUA2.png" /></a></button>
             </div>
		

    		
             <div id="header">

                
                <div id="slogan-holder"><% out.print(res.traduz(186,traducao)); %>.</div>
                    <div id="logo-holder">
                        <a href="#" title="Home">
                                <img src=".\imagens\logotipo.png" alt="" width="150" height="100" />
                        </a>
                    </div>
             
	

	<%---<div class="login-holder">
	   <form name="login"  action="" method="post">
                <label class="email-holder">
                   <input type="text" name="email" id="email" placeholder="E-mail" />
                </label>
		<input type="password" name="password" placeholder="password" />
		<input type="submit" value="" />
            </form>
		<div class="options">
			<a href="#"><% out.print(res.traduz(184,traducao)); %></a> | <a href="*" ><% out.print(res.traduz(185,traducao)); %></a>
		</div>
	</div>--%>
    
        </div>
        
                
                <!---Upload de imagens--->
        
      <!---  <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-fixed-top .navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   <a class="navbar-brand" href="">Upload de Imagens</a>
                    <a class="navbar-brand" href="imagens3.jsp">Voltar</a>
                    <a class="navbar-brand" href="">Finalizar</a>
                    
                </div>

            </div>
        </div>--->
      
       <div id="migalhas">
            <span class="mensagem" title="Ir para o Inicio"><% out.print(res.traduz(264,traducao));%></span>
            <a class="caminho" href="./imagens3.jsp" title="Ir para o Inicio"><% out.print(res.traduz(244,traducao));%></a> »
            <a class="caminho" href="./imagens3.jsp" ><% out.print(res.traduz(208,traducao));%></a> »
            <a class="caminho" href="./imagens3.jsp"><% out.print(res.traduz(224,traducao));%></a> »
            <a class="caminho"><% out.print(res.traduz(265,traducao));%>.</a>
            <!--Include.-->
        </div>
        
        <div class="container">
           <!-- <h1></h1>
            <h2 class="lead"></h2>
            <ul class="nav nav-tabs">

                <li class="active"><a href="CadastroImg.jsp">Carregar Imagens..</a></li>

            </ul>
            <br>-->
               <div id="contactform"><!--- formulario--->
            
            <!-- The file upload form used as target for the file upload widget -->
            <form name="form" id="fileupload" action="upload.jsp" method="POST" enctype="multipart/form-data">
                <!-- Redirect browsers with JavaScript disabled to the origin page -->
                <noscript><input type="hidden" name="redirect" value=""></noscript>
                <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
                <div class="row fileupload-buttonbar">
                    <div class="col-lg-7">
                        <!-- The fileinput-button span is used to style the file input field as button -->
                        <span class="btn btn-success fileinput-button">
                            <i class="glyphicon glyphicon-plus"></i>
                            <span>Adicionar...</span>
                            <input type="file" name="files[]" id="files" multiple>
                        </span>
                        <label for="file"></label>
                        <button type="submit" class="btn btn-primary start">
                            <i class="glyphicon glyphicon-upload"></i>
                            <span>Iniciar upload</span>
                        </button>
                        <button type="reset" class="btn btn-warning cancel">
                            <i class="glyphicon glyphicon-ban-circle"></i>
                            <span>Cancelar upload</span>
                        </button>
                        <!--<button type="button" class="btn btn-danger delete">
                            <i class="glyphicon glyphicon-trash"></i>
                            <span>Excluir</span>
                        </button>
                        <input type="checkbox" class="toggle">--->
                        <!-- The global file processing state -->
                        <span class="fileupload-process"></span>
                    </div>
                    <!-- The global progress state -->
                    <div class="col-lg-5 fileupload-progress fade">
                        <!-- The global progress bar -->
                        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                        </div>
                        <!-- The extended global progress state -->
                        <div class="progress-extended">&nbsp;</div>
                    </div>
                </div>
                <!-- The table listing the files available for upload/download -->
                <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
               
            </form>
             
            <br>

        </div>
           <a href="imagens3.jsp"  class="css_btn_class"  title="Concluir e Voltar" >Concluir e voltar</a>
            
            
                
                
        <!-- The blueimp Gallery widget -->
        <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
            <div class="slides"></div>
            <h3 class="title"></h3>
            <a class="prev">‹</a>
            <a class="next">›</a>
            <a class="close">×</a>
            <a class="play-pause"></a>
            <ol class="indicator"></ol>
        </div>
            
        </div>
        
        
         <!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processando...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Iniciar</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancelar</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Limpar</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
        <script src="js/jquery.ui.widget.js"></script>
        <!-- The Templates plugin is included to render the upload/download listings -->
        <script src="http://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
        <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
        <script src="http://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
        <!-- The Canvas to Blob plugin is included for image resizing functionality -->
        <script src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
        <!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
        <script src="http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <!-- blueimp Gallery script -->
        <script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
        <!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
        <script src="js/jquery.iframe-transport.js"></script>
        <!-- The basic File Upload plugin -->
        <script src="js/jquery.fileupload.js"></script>
        <!-- The File Upload processing plugin -->
        <script src="js/jquery.fileupload-process.js"></script>
        <!-- The File Upload image preview & resize plugin -->
        <script src="js/jquery.fileupload-image.js"></script>
        <!-- The File Upload audio preview plugin -->
        <script src="js/jquery.fileupload-audio.js"></script>
        <!-- The File Upload video preview plugin -->
        <script src="js/jquery.fileupload-video.js"></script>
        <!-- The File Upload validation plugin -->
        <script src="js/jquery.fileupload-validate.js"></script>
        <!-- The File Upload user interface plugin -->
        <script src="js/jquery.fileupload-ui.js"></script>
        <!-- The main application script -->
       <script src="js/main.js"></script>
        <!-- The XDomainRequest Transport is included for cross-domain file deletion for IE 8 and IE 9 -->
        <!--[if (gte IE 8)&(lt IE 10)]>
        <script src="js/cors/jquery.xdr-transport.js"></script>
        <![endif]-->
    </body> 
</html>

