<%-- 
    Document   : imagens3
    Created on : 16/02/2015, 13:54:57
    Author     : Valdomiro
--%>

<%@page import="java.sql.ResultSetMetaData"%>
<%@page import="java.sql.DriverManager"%>
<%@page import="java.sql.ResultSet"%>
<%@page import="java.sql.Statement"%>
<%@page import="java.sql.Connection"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<% 
      if(session.getValue("loginUsuario") == null && session.getValue("senhaUsuario") == null){
            response.sendRedirect("Home.jsp");
       }else 
       {
           String permissao= (String) session.getValue("permissaoUsuario");
           String array[] = new String[4];  
           array = permissao.split("-");
           if(array[1].toString().charAt(1)!='1'){
             response.sendRedirect("Home.jsp");
           }
       }
    %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="css/Efeito.css" type="text/css" media="screen" />
        <script type="text/javascript" src="js/script.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
        <script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/functions.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="css/custom.css" type="text/css" media="screen" />
        <title></title>
        <style type="text/css">
.css_btn_class {
	font-size:16px;
	font-family:Arial;
	font-weight:normal;
	-moz-border-radius:8px;
	-webkit-border-radius:8px;
	border-radius:8px;
	border:1px solid #d83526;
	padding:9px 18px;
	text-decoration:none;
	background:-moz-linear-gradient( center top, #fe1a00 5%, #ce0100 100% );
	background:-ms-linear-gradient( top, #fe1a00 5%, #ce0100 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#fe1a00', endColorstr='#ce0100');
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #fe1a00), color-stop(100%, #ce0100) );
	background-color:#fe1a00;
	color:#ffffff;
	display:inline-block;
	text-shadow:1px 1px 0px #b23e35;
 	-webkit-box-shadow:inset 1px 1px 0px 0px #f29c93;
 	-moz-box-shadow:inset 1px 1px 0px 0px #f29c93;
 	box-shadow:inset 1px 1px 0px 0px #f29c93;
}.css_btn_class:hover {
	background:-moz-linear-gradient( center top, #ce0100 5%, #fe1a00 100% );
	background:-ms-linear-gradient( top, #ce0100 5%, #fe1a00 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ce0100', endColorstr='#fe1a00');
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #ce0100), color-stop(100%, #fe1a00) );
	background-color:#ce0100;
}.css_btn_class:active {
	position:relative;
	top:1px;
}
/* This css button was generated by css-button-generator.com */

</style>
        
<script language="JavaScript" type="text/javascript">
   
   function confirmBox(a) {

    var r= confirm("Deseja mesmo Remover ?"); 
    if( r== true){
        //window.location.href="SetAlteracaoPimentas.jsp";
         //document.getElementById("contactform").submit();
         
           RemoveTableRow(a);
           return true;

    }else
    {
        location.href="imagens3.jsp";
        return false;
    }
        
   }

</script>
<script type="text/javascript">
      $(document).ready(function() {
          
            $('button').click(function() {
                //var id = $(this).attr('id');
                var name = $(this).attr('name');
                //var value = $(this).attr('value');
                //alert("Nome "+name);
                if(confirmBox(aux($(this)))){
                $.post('removeimg.jsp',{nome: name},function(data){
                    var x = parseInt(data);
                    if(x==1){ 
                       alert("Imagem removida com sucesso  !");
                   }
                });
            }
                
                });
                $('input:submit').click(function() {
                //var id = $(this).attr('id');
                var name = $(this).attr('name');
                //var value = $(this).attr('value');
                //alert(id+" "+name+" "+value)
                $.post('Clear.jsp',{id:name},function(data){
                    var x = parseInt(data);
                    if(x==0){ 
                       alert("Nenhum dado foi recebido!");
                   }else if(x==1)
                   {
                       //alert("Ok");
                   }
                });
                
                });

           
    
   });      

      </script>
    </head>
    <body>
       
        <%@include file="Cabecalho.jsp" %>
        <%@include file="menu.jsp" %>
        
        <div id="migalhas">
            <span class="mensagem" title="Ir para o Inicio"><% out.print(res.traduz(264,traducao));%></span>
            <a class="caminho" href="./localizacao3.jsp" title="Ir para o Inicio"><% out.print(res.traduz(244,traducao));%></a> »
            <a class="caminho" href="./localizacao3.jsp" ><% out.print(res.traduz(210,traducao));%></a> »
            <a class="caminho" href=""><% out.print(res.traduz(224,traducao));%></a> »
            <a class="caminho"><% out.print(res.traduz(248,traducao));%>.</a>
            <!--Include.-->
        </div>
        
        <jsp:useBean id="temp" class="meupacote.processaDB" />
        <ul id="nav2">
	    <li class=""><a href="localizacao3.jsp"><% out.print(res.traduz(223,traducao));%></a></li>
	    <li class="active"><a href="faseplantula3.jsp"><% out.print(res.traduz(224,traducao));%></a></li>
	   <%-- <li class=""><a href="#"><% out.print(res.traduz(225,traducao));%></a></li>
	    <li class=""><a href=""><% out.print(res.traduz(226,traducao));%></a></li>
	    <li class=""><a href=""><% out.print(res.traduz(227,traducao));%></a></li>--%>
	</ul>
        <ul id="nav3">
            <li class=""><a href="faseplantula3.jsp"><% out.print(res.traduz(4,traducao));%></a></li>
            <li class=""><a href="fasevegetativa3.jsp"><% out.print(res.traduz(28,traducao));%></a></li>
            <li class=""><a href="fasereprodutiva3.jsp"><% out.print(res.traduz(67,traducao));%></a></li>
            <li class="active"><a href="imagens3.jsp"><% out.print(res.traduz(248,traducao));%></a></li>
            <li class=""><a href="CadastroImg.jsp">Add Imagens</a></li>
        </ul>
        <br>
        <br>
        <br>
        
                                
            <%
             
                 int cod=0 ;//= Integer.parseInt(request.getParameter("chave"));
                 int linhas=0;
                 if(session.getValue("esc")!=null){
                    cod = Integer.parseInt(session.getValue("esc").toString());
                 }
                 
                 
                
          
          Connection conn =null;
          Statement st= null;
          ResultSet rs =null;
         
          try{
              
              Class.forName("com.mysql.jdbc.Driver").newInstance();
              conn = DriverManager.getConnection("jdbc:mysql://localhost/sisgermo","root","");
              st = conn.createStatement();
              rs = st.executeQuery("Select* from imagens where identificador = '"+cod+"'");
              //String traducao="por";
              linhas=0;
              
              //out.println("Quantidade de linhas"+linhas);
             if(temp.getTamanho(cod)>0) 
              {
                //linhas=1;
            %>
            <div class="tab">
            <form id="contactform" method="post" action="">
                
            <table cellspacing="0" id="myTable" summary="Tabela de dados">
            <thead>
              <tr>
                <!--<th><input type="checkbox" value="1" id="marcar-todos" name="marcar-todos" /></th>-->
                <th></th>
                <th><% out.print(res.traduz(251,traducao));%></th>
                <th><% out.print(res.traduz(249,traducao));%></th>
                <th><% out.print(res.traduz(248,traducao));%></th>
                <th><% out.print(res.traduz(250,traducao));%></th>
              </tr>
            </thead>
            <%
               
              while(rs.next()){
                  %>
                 <tbody>
                    <tr>
                      <td><input type="checkbox" value="1" name="marcar[]" /></td>
                      <td><% out.print(rs.getString("identificador"));%></td>
                      <td><% out.print(rs.getString("nome"));%></td>
                      <%
                          String caminho="";
                          caminho= "./fotos/"+rs.getString("nome");
                      %>
                      <td><img src="<% out.print(caminho); %>" width="125" height="125"></td>
                     <!-- <td></td>--->
                     <!-- <td>
                        
                        <a href="#"><img src="./imagens/del.ico" width="35" height="35" title="Excluir"  /></a>
                      </td>-->
                      <td class="actions">
		      <!-- <button class="delete" onclick="RemoveTableRow(this)" type="button">Remove</button>--->
                       <button type="button" name="<% out.print(rs.getString("nome")); %>" onclick="aux(this)"  class="css_btn_class">Remover</button>
		      </td>
                    </tr>
                   </tbody>
              <%    
                  
              }//final do while
             }// if
          }
          catch(Exception ex)
          {
              out.println(ex);
              ex.printStackTrace();
          }finally{
              if(rs!=null) 
                  rs.close();
              if(st!=null)
                  st.close();
              if(conn!=null) 
                  conn.close();
          }
         %>
        
        </table>
         <% if(temp.getTamanho(cod)>0){ %>
          <input type="Submit" name="<%out.print(cod);%>"  class="button" value="<% out.print(res.traduz(253,traducao));%> >>" onclick="sucess()" />
          <input type="button" name="Submit"  class="button" value="<% out.print(res.traduz(252,traducao));%> >>" onclick="goNext4()" />
           <input type="button" name="Submit"  class="button" value="<< <% out.print(res.traduz(247,traducao));%>" onclick="goBack4()" />
            </form>
            </div>
            <%} %>
            <% if(temp.getTamanho(cod)<1){ %>
                    <div class="tab">
                         <form id="contactform" method="post" action=".jsp">
                           <img src="./imagens/semImagem.jpg" width="650" height="380">
                           <br>
                           <br>
                           <input type="Submit" name="<%out.print(cod);%>" id="con"  class="button" value="<% out.print(res.traduz(253,traducao));%> >>" onclick="sucess()" />
                           <input type="button" name="Submit"  class="button" value="<% out.print(res.traduz(252,traducao));%> >>" onclick="goNext4()" />
                           <!-- <input type="button" name="Submit"  class="button" value="<< <% out.print(res.traduz(247,traducao));%>" onclick="goBack4()" />--->
                         </form>
                    </div>
                     
                   <% }
            %>
            
    
          <br>
          <br>
          <%@include file="rodape.jsp" %> 
   <script>
    $(function(){
      
      $('table > tbody > tr:odd').addClass('odd');
      
      $('table > tbody > tr').hover(function(){
        $(this).toggleClass('hover');
      });
      
      $('#marcar-todos').click(function(){
        $('table > tbody > tr > td > :checkbox')
          .attr('checked', $(this).is(':checked'))
          .trigger('change');
      });
      
      $('table > tbody > tr > td > :checkbox').bind('click change', function(){
        var tr = $(this).parent().parent();
        if($(this).is(':checked')) $(tr).addClass('selected');
        else $(tr).removeClass('selected');
      });
      
      $('form').submit(function(e){ e.preventDefault(); });
      
      $('#pesquisar').keydown(function(){
        var encontrou = false;
        var termo = $(this).val().toLowerCase();
        $('table > tbody > tr').each(function(){
          $(this).find('td').each(function(){
            if($(this).text().toLowerCase().indexOf(termo) > -1) encontrou = true;
          });
          if(!encontrou) $(this).hide();
          else $(this).show();
          encontrou = false;
        });
      });
      
      $("table") 
        .tablesorter({
          dateFormat: 'uk',
          headers: {
            0: {
              sorter: false
            },
            5: {
              sorter: false
            }
          }
        }) 
        .tablesorterPager({container: $("#pager")})
        .bind('sortEnd', function(){
          $('table > tbody > tr').removeClass('odd');
          $('table > tbody > tr:odd').addClass('odd');
        });
      
    });
    </script>
			
         
        
    </body>
</html>
